name = "zionsberg"
compatibility_date = "2024-04-09"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".open-next/assets"

[vars]
NEXT_PUBLIC_SANITY_PROJECT_ID = "t90obuqv"
NEXT_PUBLIC_SANITY_DATASET = "production"
